"""Automated Test Suite for One-Time Extension Setup & Toolbar Pinning (IMP-2026-0916-001).

Validates:
- POST /api/v1/settings/setup-extension execution & response contract
- Preferences JSON modern toolbar pinning (toolbar.pinned_actions + extensions.pinned_extensions)
- DB settings persistence of extension_setup_verified and timestamp
- Browser runner persistent profile selection
"""

import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest
from httpx import ASGITransport, AsyncClient

from app.automation.browser_manager import ChromeSession
from app.automation.session_runner import SingleSessionBrowserRunner
from app.main import app
from app.services.settings_service import get_system_settings_async


@pytest.mark.asyncio
async def test_persistent_profile_toolbar_pinning_preferences(tmp_path: Path):
    """Verify ChromeSession.configure_and_pin_profile writes modern Chromium toolbar.pinned_actions."""
    profile_dir = tmp_path / "browser_profile"
    result_dir = ChromeSession.configure_and_pin_profile(
        profile_dir=profile_dir,
        api_key="test_dummy_key_123",
    )

    assert result_dir.is_dir()
    pref_file = result_dir / "Default" / "Preferences"
    assert pref_file.is_file(), "Default/Preferences must be generated by configure_and_pin_profile"

    prefs = json.loads(pref_file.read_text(encoding="utf-8"))

    # 1. Verify extensions.pinned_extensions
    pinned_exts = prefs.get("extensions", {}).get("pinned_extensions", [])
    assert "gcpdbjbmekkdlkpldjgffhmapgpdlcpj" in pinned_exts

    # 2. Verify modern Chromium (v115+) toolbar.pinned_actions
    pinned_actions = prefs.get("toolbar", {}).get("pinned_actions", [])
    expected_action_id = "kActionExtensionId:gcpdbjbmekkdlkpldjgffhmapgpdlcpj"
    assert expected_action_id in pinned_actions or "gcpdbjbmekkdlkpldjgffhmapgpdlcpj" in pinned_actions

    # 3. Verify browser toolbar menu is enabled
    assert prefs.get("browser", {}).get("show_extensions_toolbar_menu") is True
    assert prefs.get("extensions", {}).get("developer_mode") is True


@pytest.mark.asyncio
async def test_setup_extension_endpoint_success(mocker, tmp_path):
    """Verify POST /api/v1/settings/setup-extension returns 200 with verified diagnostics."""
    mock_session = MagicMock()
    mock_session.start = AsyncMock(return_value=MagicMock())
    mock_session.close = AsyncMock()
    mock_session.extension_loaded = True
    mock_session.service_worker_active = True
    mock_session.extension_id = "gcpdbjbmekkdlkpldjgffhmapgpdlcpj"

    mock_profile = tmp_path / "data" / "browser_profile"
    mock_profile.mkdir(parents=True, exist_ok=True)

    mock_session_cls = MagicMock()
    mock_session_cls.configure_and_pin_profile.return_value = mock_profile
    mock_session_cls.return_value = mock_session
    mocker.patch("app.api.v1.endpoints.settings.ChromeSession", mock_session_cls)

    async def mock_run_coro(fn):
        return await fn()

    mocker.patch("app.api.v1.endpoints.settings.run_browser_coroutine", side_effect=mock_run_coro)

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        resp = await client.post(
            "/api/v1/settings/setup-extension",
            json={"anticaptcha_api_key": "28b486b8f31f74c6bf4453735815aa53"},
        )

    assert resp.status_code == 200, f"Expected 200 OK but got {resp.status_code}: {resp.text}"
    data = resp.json()
    assert data["success"] is True
    assert data["extension_id"] == "gcpdbjbmekkdlkpldjgffhmapgpdlcpj"
    assert "data" in data["profile_dir"] or "browser_profile" in data["profile_dir"]
    assert data["verified_at"] is not None


@pytest.mark.asyncio
async def test_settings_persistence_extension_verified():
    """Verify get_system_settings_async reflects extension_setup_verified flag."""
    current_settings = await get_system_settings_async()
    assert hasattr(current_settings.automation, "extension_setup_verified")
    assert hasattr(current_settings.automation, "extension_setup_timestamp")


def test_scraper_runtime_selects_persistent_profile(tmp_path: Path):
    """Verify SingleSessionBrowserRunner selects persistent profile when available."""
    runner = SingleSessionBrowserRunner(
        headless=True,
        user_data_dir=str(tmp_path / "custom_profile"),
    )
    (tmp_path / "custom_profile").mkdir()
    # The runner must use the configured user_data_dir rather than creating a random temp dir
    assert runner.user_data_dir == str(tmp_path / "custom_profile")
